version: "2.2"
services:

  timesheet:
    image: "nassimbenali/timesheet-devops:1.0"
    ports:
      - "8082:8082"
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/timesheet-devops-db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    depends_on:
      - mysql


  mysql:
    image: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=timesheet-devops-db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my_net




